[tool.poetry]
name = "dopy-standalone"
version = "0.1.0"
description = ""
authors = ["Navdeep Saini <navdeep@mailbox.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
